services:
  data-generation-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/data_generation_runner.py
    network_mode: host

  backtesting-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/backtesting_runner.py
    network_mode: host

  db-status-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/db_status_runner.py
    network_mode: host

  candles-downloader-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/candles_downloader_runner.py
    network_mode: host

  screener-runner:
    image: hummingbot/quants-lab:latest
    volumes:
      - .:/quants-lab
    env_file:
      - .env
    command: conda run --no-capture-output -n quants-lab python3 tasks/screener_runner.py
    network_mode: host
