version: '3.8'

services:
  base-task-runner:
    image: hummingbot/quants_lab:latest
    volumes:
      - ./data:/quants-lab/data
      - ./core:/quants-lab/core
      - ./tasks:/quants-lab/tasks
      - ./research_notebooks:/quants-lab/research_notebooks
      - ./controllers:/quants-lab/controllers
      - ./services:/quants-lab/services
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TIMESCALE_HOST=${TIMESCALE_HOST}
      - OPTUNA_HOST=${OPTUNA_HOST}
    command: conda run --no-capture-output -n quants-lab python3 tasks/task_runner.py
    networks:
      - quants-lab-network
    depends_on:
      - timescaledb
      - optuna-db  # Ensure Optuna database starts first

  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TIMESCALE_HOST=${TIMESCALE_HOST}
      - POSTGRES_DB=timescaledb
    volumes:
      - timescale-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - quants-lab-network

  optuna-db:
    container_name: optuna-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OPTUNA_HOST=${OPTUNA_HOST}
      - POSTGRES_DB=optimization_database
    volumes:
      - optuna-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - quants-lab-network

networks:
  quants-lab-network:
    driver: bridge

volumes:
  timescale-data:
    driver: local
  optuna-data:
    driver: local
